# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9SqwkaVmu8gVDbRhIMSJbtc5-iIg9Go
"""

import re
import io
import pandas as pd
import numpy as np
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

floor_map = {
    "地下一": -1,"地下二": -2,"地下三": -3,"地下四": -4,"地下五": -5,"地下六": -6,"地下七": -7,"地下八": -8,"地下九": -9,"地下十": -10,

    "一": 1, "二": 2, "三": 3, "四": 4, "五": 5, "六": 6, "七": 7, "八": 8, "九": 9, "十": 10,
    "十一": 11, "十二": 12, "十三": 13, "十四": 14, "十五": 15, "十六": 16, "十七": 17, "十八": 18, "十九": 19, "二十": 20,
    "二十一": 21, "二十二": 22, "二十三": 23, "二十四": 24, "二十五": 25, "二十六": 26, "二十七": 27, "二十八": 28, "二十九": 29, "三十": 30,
    "三十一": 31, "三十二": 32, "三十三": 33, "三十四": 34, "三十五": 35, "三十六": 36, "三十七": 37, "三十八": 38, "三十九": 39, "四十": 40,
    "四十一": 41, "四十二": 42, "四十三": 43, "四十四": 44, "四十五": 45, "四十六": 46, "四十七": 47, "四十八": 48, "四十九": 49, "五十": 50,
    "五十一": 51, "五十二": 52, "五十三": 53, "五十四": 54, "五十五": 55, "五十六": 56, "五十七": 57, "五十八": 58, "五十九": 59, "六十": 60,
    "六十一": 61, "六十二": 62, "六十三": 63, "六十四": 64, "六十五": 65, "六十六": 66, "六十七": 67, "六十八": 68, "六十九": 69, "七十": 70,
    "七十一": 71, "七十二": 72, "七十三": 73, "七十四": 74, "七十五": 75, "七十六": 76, "七十七": 77, "七十八": 78, "七十九": 79, "八十": 80,
    "八十一": 81, "八十二": 82, "八十三": 83, "八十四": 84, "八十五": 85, "八十六": 86, "八十七": 87, "八十八": 88, "八十九": 89, "九十": 90,
    "九十一": 91, "九十二": 92, "九十三": 93, "九十四": 94, "九十五": 95, "九十六": 96, "九十七": 97, "九十八": 98, "九十九": 99, "一百": 100,
    "一百零一": 101
}


def roc_date_parts(x):
    try:
        x = str(int(float(x))).zfill(7)

        year = int(x[:3])
        month = int(x[3:5])
        day = int(x[5:7])

        return year, month, day

    except:
        return None

def calc_house_age(trade_date, build_date):

    if pd.isna(trade_date) or pd.isna(build_date):
        return np.nan

    ty, tm, td = roc_date_parts(trade_date)
    by, bm, bd = roc_date_parts(build_date)

    months = (ty - by) * 12 + (tm - bm)

    if td < bd:
        months -= 1

    return months / 12

def parse_floor(x):

    if pd.isna(x):
        return np.nan

    x = str(x)

    matches = re.findall(
        r'(地下[一二三四五六七八九十百零]+|[一二三四五六七八九十百零]+)層',
        x
    )

    if not matches:
        return np.nan

    floors = [floor_map[m] for m in matches if m in floor_map]

    if not floors:
        return np.nan

    return max(floors)

def real_estate_crawler(year, season):

    url = "https://plvr.land.moi.gov.tw/DownloadSeason?season="+str(year)+"S"+str(season)+"&fileName=A_lvr_land_A.csv"
    res = requests.get(url, verify=False)

    if res.status_code != 200:
        print(f"下載失敗: {year}年第{season}季, 狀態碼: {res.status_code}")
        return

    df = pd.read_csv(io.BytesIO(res.content))
    df.columns = (
      df.columns
        .str.replace("(", "", regex=False)
        .str.replace(")", "", regex=False)
    )

    df["備註"] = df["備註"].replace(r'^\s*$', np.nan, regex=True)
    df = df[df["交易標的"].str.contains("房地", na=False) & df["備註"].isnull() & df["單價元平方公尺"].notnull()].copy()


    df["屋齡"] = df.apply(
        lambda row: calc_house_age(
            row["交易年月日"],
            row["建築完成年月"]
        ),
        axis=1
    )



    df["所在樓層"] = df["移轉層次"].apply(parse_floor)
    df["總樓層"] = df["總樓層數"].apply(parse_floor)
    mask = df["移轉層次"].astype(str).str.strip() == "全"
    df.loc[mask, "所在樓層"] = df.loc[mask, "總樓層"]
    df["樓層比"] = np.where(df["總樓層"] > 0, df["所在樓層"] / df["總樓層"], np.nan)

    df["電梯"] = df["電梯"].fillna("未知")

    cols_to_convert = ["建物移轉總面積平方公尺", "主建物面積", "附屬建物面積", "陽台面積", "車位移轉總面積平方公尺", "車位總價元"]

    for col in cols_to_convert:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
            df[col] = df[col].fillna(0)


    df["車位移轉總面積平方公尺"] = df["車位移轉總面積平方公尺"].fillna(0)
    df["車位單價"] = np.where(df["車位移轉總面積平方公尺"] > 0, df["車位總價元"] / df["車位移轉總面積平方公尺"], np.nan)


    df["公設面積"] = df["建物移轉總面積平方公尺"] - df["主建物面積"] - df["附屬建物面積"] - df["陽台面積"]
    df["公設面積"] = df["公設面積"].clip(lower=0)



    drop_cols = [
        "總價元",
        "編號",
        "移轉編號",
        "備註",
        "交易年月日",
        "建築完成年月",
        "交易筆棟數",
        "非都市土地使用編定",
        "非都市土地使用分區"
    ]
    df = df.drop(columns=drop_cols, errors="ignore")
    return df

from sklearn.model_selection import train_test_split

def split_data(
    df,
    target_col="單價元平方公尺",
    test_size=0.2,
    random_state=42
):
    df = df.replace([np.inf, -np.inf], np.nan)

    cat_cols = df.select_dtypes(include=["object"]).columns

    for col in cat_cols:
        df[col] = df[col].astype("category")

    df[target_col] = pd.to_numeric(df[target_col], errors="coerce")
    df = df.dropna(subset=[target_col])

    X = df.drop(columns=[target_col])
    y = df[target_col].astype(float)

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=test_size,
        random_state=random_state
    )

    return X_train, X_test, y_train, y_test

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

def preprocess_data(X_train):

    numeric_features = X_train.select_dtypes(
        include=["number"]
    ).columns

    categorical_features = X_train.select_dtypes(
        exclude=["number"]
    ).columns

    numeric_transformer = Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ])

    categorical_transformer = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer([
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ])

    return preprocessor

from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

from xgboost import XGBRegressor

def train_xgboost(
    X_train,
    X_test,
    y_train,
    y_test,
    preprocessor
):

    model = Pipeline([
        ("preprocessor", preprocessor),
        ("regressor", XGBRegressor(
            n_estimators=1000,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            n_jobs=-1
        ))
    ])

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    print(f"MAE  = {mae:.2f}")
    print(f"RMSE = {rmse:.2f}")
    print(f"R²   = {r2:.4f}")
    return model, y_pred

import matplotlib.pyplot as plt

def visualize_result(y_test, y_pred):

    plt.figure(figsize=(8, 6))

    plt.scatter(
        y_test,
        y_pred,
        alpha=0.6
    )

    plt.plot(
        [y_test.min(), y_test.max()],
        [y_test.min(), y_test.max()],
        'r--'
    )

    plt.xlabel("Actual Price")
    plt.ylabel("Predicted Price")
    plt.title("Actual vs Predicted")

    plt.tight_layout()
    plt.show()

def visualize_residual(y_test, y_pred):

    y_test = np.array(y_test)
    y_pred = np.array(y_pred)

    plt.figure(figsize=(8, 6))

    plt.scatter(y_test, y_pred, alpha=0.6)

    mn = min(y_test.min(), y_pred.min())
    mx = max(y_test.max(), y_pred.max())

    plt.plot([mn, mx], [mn, mx], 'r--')

    plt.xlabel("Actual Price")
    plt.ylabel("Predicted Price")
    plt.title("Actual vs Predicted")

    plt.tight_layout()
    plt.show()

all_df = []

for year in range(102, 115):
    for season in range(1, 5):
        df_tmp = real_estate_crawler(year, season)

        if df_tmp is not None:
            all_df.append(df_tmp)

df = pd.concat(all_df, ignore_index=True)
df.to_csv('A_lvr_land_A.csv', index=False, encoding='utf-8-sig')

X_train, X_test, y_train, y_test = split_data(df)

preprocessor = preprocess_data(X_train)

model, y_pred = train_xgboost(
    X_train,
    X_test,
    y_train,
    y_test,
    preprocessor
)

visualize_result(y_test, y_pred)

visualize_residual(y_test, y_pred)